#!/bin/bash

   ##########################################################################
   #                                                                        #
   #   Copyright (c) 2019 Paul Keir, University of the West of Scotland.    #
   #                                                                        #
   ##########################################################################

usage() { echo bsyclcc: error: $2 >&2; exit $1; }

[ $# -eq 0      ] && usage 1 "no input files"
[ -z "$COMPUTECPP_DIR" ] && usage 2 "create and initialise a COMPUTECPP_DIR environment var"

COMPILE_ONLY=0
PREPROCESS_ONLY=0
USE_GCC=0

while [[ $# > 0 ]]; do
  case "$1" in
    -E)   PREPROCESS_ONLY=1; CMD="$CMD $1" ;;
    -c)      COMPILE_ONLY=1; CMD="$CMD $1" ;;
    -syclcc-use-host) USE_GCC=1; CMD="$CMD" ;;
    *)                       CMD="$CMD $1" ;;
  esac
  shift # $2 becomes $1; $3 becomes $2 etc.
done

if ((!USE_GCC)); then
  if ((!COMPILE_ONLY && !PREPROCESS_ONLY)); then CMD="$CMD -L $COMPUTECPP_DIR/lib -lComputeCpp"; fi

# SYCL_LANGUAGE_VERSION can also be 2017
  $COMPUTECPP_DIR/bin/compute++ -O2 -mllvm -inline-threshold=1000 -Wno-unused-command-line-argument -sycl-driver -sycl-target spir64 -no-serial-memop -I $COMPUTECPP_DIR/include -std=c++17 -DSYCL_LANGUAGE_VERSION=202001 $CMD
else
  g++ $CMD
fi

exit $?
