#!/bin/bash

   ##########################################################################
   #                                                                        #
   #   Copyright (c) 2019 Paul Keir, University of the West of Scotland.    #
   #                                                                        #
   ##########################################################################

usage() { echo bsyclcc: error: $2 >&2; exit $1; }

[ $# -eq 0      ] && usage 1 "no input files"
[ -z "$COMPUTECPP_DIR" ] && usage 2 "create and initialise a COMPUTECPP_DIR environment var"

COMPILE_ONLY=0
PREPROCESS_ONLY=0

while [[ $# > 0 ]]; do

  case "$1" in
    -E)   PREPROCESS_ONLY=1; CMD="$CMD $1" ;;
    -c)      COMPILE_ONLY=1; CMD="$CMD $1" ;;
    *)                       CMD="$CMD $1" ;;
  esac
  shift # $2 becomes $1; $3 becomes $2 etc.
done

if ((!COMPILE_ONLY && !PREPROCESS_ONLY)); then CMD="$CMD -L $COMPUTECPP_DIR/lib -lComputeCpp"; fi

$COMPUTECPP_DIR/bin/compute++ -O2 -mllvm -inline-threshold=1000 -sycl-driver -sycl-target spir64 -no-serial-memop -I $COMPUTECPP_DIR/include -std=c++11 $CMD

exit $?
