#!/bin/bash

   ##########################################################################
   #                                                                        #
   # Copyright (c) 2016-2017 Paul Keir, University of the West of Scotland. #
   #                                                                        #
   ##########################################################################

usage() { echo syclcc: error: $2 >&2; exit $1; }

[ -z "$COMPUTECPP" ] && usage 2 "create and initialise a COMPUTECPP environment var"

BASEDIR=$(dirname "$0")
COMPUTECPP_BASENAME=`basename "$COMPUTECPP"`
SYCLCC_FILENAME=syclcc-$COMPUTECPP_BASENAME.sh
$BASEDIR/$SYCLCC_FILENAME "$@"
exit $?

