#!/bin/bash

   ##########################################################################
   #                                                                        #
   # Copyright (c) 2016-2017 Paul Keir, University of the West of Scotland. #
   #                                                                        #
   ##########################################################################

usage() { echo syclcc: error: $2 >&2; exit $1; }

[ -z "$COMPUTECPP_DIR" ] && usage 2 "create and initialise a COMPUTECPP_DIR environment var"

COMPUTECPP_DIR_BASENAME=`basename "$COMPUTECPP_DIR"`
SYCLCC_FILENAME=syclcc-$COMPUTECPP_DIR_BASENAME.sh
$SYCLCC_FILENAME "$@"
exit $?

