#!/bin/bash

     #####################################################################
     #                                                                   #
     # Copyright (c) 2015 Paul Keir, University of the West of Scotland. #
     #                                                                   #
     #####################################################################

TRISYCL_CXX=g++    # Don't use $CXX as $CXX may reference this script.

usage() { echo trisyclcc: error: $2 >&2; exit $1; }

[ $# -eq 0      ] && usage 1 "no input files"
[ -z "$TRISYCL" ] && usage 2 "create and initialise a TRISYCL environment var"

$TRISYCL_CXX -D__TRISYCL__ -I$TRISYCL/include "$@"
