#!/bin/bash

#########################################################################################
#                                                                                       #
# Copyright (c) 2019 Andrew Gozillon and Paul Keir, University of the West of Scotland. #
#                                                                                       #
#########################################################################################

usage() { echo trisyclcc: error: $2 >&2; exit $1; }

[ $# -eq 0      ] && usage 1 "no input files"
[ -z "$TRISYCL_DIR" ] && usage 2 "create and initialise a TRISYCL_DIR environment var"
[ -z "$TRISYCL_TARGET" ] && usage 2 "create and initialise a TRISYCL_TARGET environment var"

TRISYCLCC_FILENAME=trisyclcc-$TRISYCL_TARGET.sh
$TRISYCLCC_FILENAME "$@"
exit $?
