#!/bin/bash

   ##########################################################################
   #                                                                        #
   # Copyright (c) 2016-2017 Paul Keir, University of the West of Scotland. #
   #                                                                        #
   ##########################################################################

usage() { echo computecppcc: error: $2 >&2; exit $1; }

[ -z "$COMPUTECPP_DIR" ] && usage 2 "create and initialise a COMPUTECPP_DIR environment var"

COMPUTECPP_DIR_BASENAME=`basename "$COMPUTECPP_DIR"`
COMPUTECPPCC_FILENAME=computecppcc-$COMPUTECPP_DIR_BASENAME.sh
$COMPUTECPPCC_FILENAME "$@"
exit $?
